### ISSUE TITLE
rospy installation problem

### ISSUE THREAD

**Issue by wd-hub** [cdevin/objectattention#1]
Thanks for your codes, so far everything works well except the bbox_node.py script.
Because the rospy module cannot be imported sucessfully, 'pip install rospy' does not work and I cannot find the solution with google. 
Is there anyone who knows this problem?
Thanks very much!

**Comment by cdevin** [comment]
Hi, do have ROS installed on your system? if so, what version?

**Comment by wd-hub** [comment]
I haven't installed ROS in my computer. 
Should I first install ROS and then 'pip install rospy'? 
If yes, which version should I use?
Thanks again!

**Comment by cdevin** [comment]
The bbox_node script is just for listening to images sent on ROS (a message passing interface for robots), applying the attention, and sending back object coordinates. If you are not using this on a robot, you do not need ROS or bbox_node. If you are using a robot or the gazebo simulator, then you should follow the ROS instructions for that robot. If you are using mujoco, then I'm working on a plugin to gym/rllab, let me know if that would be useful.

**Comment by wd-hub** [comment]
I see, so far I haven't do the experiment with robot or related simulators. Currently, I focus on improving object instance recognition and pose estimation accuracy with deep learning. 
Thanks a lot for your reply.
